### ISSUE TITLE
pronto-rubocop 0.4.4 ignoring rubocop:disable

### ISSUE THREAD

**Issue by dankohn** [mmozuras/pronto-rubocop#13]
pronto rubocop 0.4.4 is ignoring `rubocop:disable` entries, while 0.4.3 honors them correctly.

Running rubocop on a branch produces a clean result, but running `pronto run -r=rubocop` shows me 5 Rubocop errors. Each of the Rubocop errors has been explicitly disabled in the code. 

Running `pronto run -r=rubocop --commit=$(git log --pretty=format:%H | tail -1)` shows me dozens of Rubocop errors across the whole codebase.

My repo is proprietary, but I doubt the bug is limited to me. It seems like something changed in how rubocop accepts how it is being evoked by pronto-rubocop, causing it to ignore disables. Please let me know if there's anything else I can report.

**Comment by ivan-leschinsky** [comment]
@mmozuras, how to fix this?

**Comment by dankohn** [comment]
@mmozuras Welcome back from vacation. Any ideas on a fix for this?

**Comment by ivan-leschinsky** [comment]
It is problem of rubocop, not pronto-rubocop. It is ignored only when run
without command-line, for example with pronto-rubocop.

сб, 5 сент. 2015, 22:02, Dan Kohn <notifications@github.com>:

**Comment by mmozuras** [comment]
@dankohn I'll make this bug a priority. Expect more news tomorrow :smile:

**Comment by dankohn** [comment]
@mmozuras Hugely appreciated. I love pronto. Here I am signing it's praises: https://news.ycombinator.com/item?id=10055342

**Comment by mmozuras** [comment]
@dankohn so that's where those stars came from...  But honestly, can't express how great that feels :smile: 

And the bug is fixed and released, btw :smile:
