### ISSUE TITLE
passing rubocop command line options (e.g. -DS)

### ISSUE THREAD

**Issue by tansaku** [mmozuras/pronto-rubocop#14]
I love running Rubocop with the -DS flags which give cop names and links to the documentation related to the offence.

Is there some way to pass these flags through pronto-rubocop to pronto to adjust the rubocop output?

**Comment by tansaku** [comment]
ah, I found settings in the Rubocop config file that handle this

**Comment by bolshakov** [comment]
@tansaku сould you post the solution?

**Comment by tansaku** [comment]
@bolshakov you can see all the settings in here https://github.com/bbatsov/rubocop/blob/master/config/default.yml

turn the appropriate ones on or off as you need them

**Comment by itay-grudev** [comment]
This is still relevant. I'd like to run `rubocop -P` for parallelizing the analysis.
