### ISSUE TITLE
bump Rubocop version to 0.33

### ISSUE THREAD

**Issue by tansaku** [mmozuras/pronto-rubocop#15]
I'm finding that pronto-rubocop doesn't handle this rubocop config:

```
Warning: unrecognized parameter AllCops:DisabledByDefault found in .rubocop.yml
```

I fixed this in my rubocop by upgrading to 0.33.  Is pronto-rubocop still locked to 0.32?

**Comment by mmozuras** [comment]
As of today, you should be able to update to `0.34` :smile:

**Comment by tansaku** [comment]
thanks that fixed that! much appreciated
