### ISSUE TITLE
Rubocop fail-level handling

### ISSUE THREAD

**Issue by nfm** [mmozuras/pronto-rubocop#23]
It looks like `pronto-rubocop` has hardcoded translations from Rubocop severities to Pronto levels (https://github.com/mmozuras/pronto-rubocop/blob/33793d426fba5f473038a23a2fda1971b417f396/lib/pronto/rubocop.rb#L62,L69). As a result, Pronto treats `convention` and `refactor` as informational, rather than errors, and doesn't exit with a non-zero code if offences of these categories are found.

However, Rubocop will fail and return a non-zero exit code if any offences are found (apart from `autocorrect` offences).

We'd like to have `pronto` return non-zero on CI for `convention` and `refactor` severities. Would you be open to a PR that either changed `Pronto::Rubocop#level` to do this (making it behave the same as Rubocop), or a PR that allowed the failure level to be customized?

It looks like `pronto-rubocop` is only configurable via `.rubocop.yml` (which I don't think you can use to configure Rubocop's `--fail-level`), so I'm not sure what the best approach would be for the latter. If you have any pointers for implementation that would be helpful.

Thanks!

**Comment by mmozuras** [comment]
@nfm you can configure severity for cops (single or multiple) in `.rubocop.yml`:
http://rubocop.readthedocs.io/en/latest/configuration/#severity

Looking at `rubocop` source code:

```ruby
      def default_severity
        self.class.lint? ? :warning : :convention
      end
```

I think that it makes sense to translate `:convention` to `:warning`. Not sure about `:refactor` though. @nfm thoughts on `:refactor`?

**Comment by nfm** [comment]
@mmozuras Thanks, I didn't know you could configure the severity like that :)

I'm not sure about `:refactor` either! I'm having a hard time figuring out when Rubocop actually uses that severity. Translating `:refactor` to `:warning` would be consistent with Rubocop's [#minimum_severity_to_fail](https://github.com/bbatsov/rubocop/blob/6907b13320493b334dc60a1a7687fc381f1f3740/lib/rubocop/runner.rb#L306-L311), but I don't have a very strong feeling about it.

**Comment by patrickdavey** [comment]
I'm not quite seeing how to do this.

I would also like basically any failure from Rubocop to raise an error.

I tried adding

```ruby
AllCops:
  Severity: error
```
but that didn't seem to do the trick. Is there an easy way to do this?
